// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/jasonzhao47/goTrainingCamp/hw5/webook/internal/repository"
	"github.com/jasonzhao47/goTrainingCamp/hw5/webook/internal/repository/cache"
	"github.com/jasonzhao47/goTrainingCamp/hw5/webook/internal/repository/dao"
	"github.com/jasonzhao47/goTrainingCamp/hw5/webook/internal/service"
	"github.com/jasonzhao47/goTrainingCamp/hw5/webook/internal/web"
	"github.com/jasonzhao47/goTrainingCamp/hw5/webook/internal/web/jwt"
	"github.com/jasonzhao47/goTrainingCamp/hw5/webook/ioc"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJWTHandler(cmdable)
	loggerV1 := ioc.InitLogger()
	v := ioc.InitGinMiddlewares(cmdable, handler, loggerV1)
	db := ioc.InitDB(loggerV1)
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSMSService()
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, handler, codeService)
	articleDAO := dao.NewArticleGORMDAO(db)
	articleCache := cache.NewArticleRedisCache(cmdable)
	articleRepository := repository.NewCachedArticleRepository(articleDAO, userRepository, articleCache)
	articleService := service.NewArticleService(articleRepository)
	articleHandler := web.NewArticleHandler(loggerV1, articleService)
	//wechatService := ioc.InitWechatService(loggerV1)
	//oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, handler, userService)
	engine := ioc.InitWebServer(v, userHandler, articleHandler)
	return engine
}
