apiVersion: v1
kind: Service
metadata:
  name: webook-mysql-jasonzhao47
spec:
  selector:
    app: webook-mysql-jasonzhao47
  ports:
    - protocol: TCP
      # port 内部访问
      port: 3308
      targetPort: 3306
  type: LoadBalancer
  