apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webook-jasonzhao47
  template:
    metadata:
      labels:
        app: webook-jasonzhao47
    spec:
      containers:
        - name: webook
          image: jasonzhao47/webook:v0.0.1
          ports:
            - containerPort: 8081