apiVersion: v1
kind: Service
metadata:
  name: webook-redis-jasonzhao47
spec:
  selector:
    app: webook-redis-jasonzhao47
  ports:
    - protocol: TCP
      # port 内部访问
      port: 6380
      # nodePort 外部访问
      nodePort: 31379
      # pod的端口
      targetPort: 6379
  type: LoadBalancer
  